//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prak2semitog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int Id { get; set; }
        public int Id_Supply { get; set; }
        public int Id_Demand { get; set; }
    
        public virtual Demands Demands { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
