//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prak2semitog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demands()
        {
            this.Deals = new HashSet<Deals>();
        }
    
        public int Id_Demand { get; set; }
        public int Id_Client { get; set; }
        public int Id_Agent { get; set; }
        public string Type_RealEstate { get; set; }
        public string Adress { get; set; }
        public Nullable<int> MinPrice { get; set; }
        public Nullable<int> MaxPrice { get; set; }
        public Nullable<int> Id_Apartment { get; set; }
        public Nullable<int> Id_House { get; set; }
        public Nullable<int> Id_Land { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deals> Deals { get; set; }
        public virtual Demand_Apartments Demand_Apartments { get; set; }
        public virtual Demand_Houses Demand_Houses { get; set; }
        public virtual Demand_Lands Demand_Lands { get; set; }
    }
}
