//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prak2semitog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Houses
    {
        public int Id_House { get; set; }
        public Nullable<int> TotalFloor { get; set; }
        public Nullable<double> TotalArea { get; set; }
        public Nullable<int> TotalRooms { get; set; }
    }
}
